version: "3.4"
services:
    web:
        image: if3110-spa-react-1:latest
        ports:
            - 5173:5173
        hostname: web
        env_file:
            - .env
        volumes:
            - .:/app/spa-react
            - /app/spa-react/node_modules
